### ISSUE TITLE
Nested functionality broken

### ISSUE THREAD

**Issue by PetarMI** [hector-sab/ttictoc#2]
When nested is set to True in the constructor the function `set_nested` checks if the boolean value actually changes the state. When `True` is passed to the constructor the variable `tstart` will remain `None` as it is inside the if statement. 

Therefore every time nested is used it blows up with an error in the append statement to `tstart`

**Comment by hector-sab** [comment]
Yup, took me 10 months to address this. The code was a mess, so I changed it to what I believe is cleaner. Nested should be working kind now.
